[package]
name = "repuff"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.2.7", features = ["derive"] }
librepuff = { path = "../librepuff" }
log = { version = "0.4" }
pretty_env_logger = { version = "0.4" }
